name: weather
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bloc_concurrency: ^0.2.1
  connectivity_plus: ^3.0.4
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  hydrated_bloc: ^9.1.0
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.3.3

  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

  mews_pedantic: ^0.13.0

flutter:
  uses-material-design: true
